#!/bin/bash
# podman-01 grader
source /opt/linux-labs/lib/grading.sh

LAB=podman-01
STATE_FILE=/opt/linux-labs/state/$LAB
CONTENT=/srv/webapp
UNIT=container-webapp.service

grade_begin podman-01
grade_require_state podman-01 "$STATE_FILE"

state_value() {
	sed -n "s/^$1=//p" "$STATE_FILE" | head -n 1
}

user=$(state_value user)
token=$(state_value token)
uid=$(id -u "$user" 2>/dev/null)
home=$(getent passwd "$user" | cut -d: -f6)
rt="/run/user/$uid"

# as_user <command...>: run a command as the task user in the user's
# runtime directory and session bus
as_user() {
	[ -n "$uid" ] && [ -d "$rt" ] || return 1
	runuser -u "$user" -- env HOME="$home" XDG_RUNTIME_DIR="$rt" \
		DBUS_SESSION_BUS_ADDRESS="unix:path=$rt/bus" "$@" </dev/null 2>/dev/null
}

# The task user's Podman has a running container named webapp
container_running() {
	local state
	state=$(as_user podman inspect --type container --format '{{.State.Status}}' webapp) || return 1
	[ "$state" = running ]
}

# Every process that listens on TCP port 8080 belongs to the task user
port_owned_by_user() {
	local pids p found=1
	pids=$(ss -H -tlnp 'sport = :8080' 2>/dev/null | grep -o 'pid=[0-9]*' | cut -d= -f2 | sort -u)
	[ -n "$pids" ] || return 1
	for p in $pids; do
		[ "$(stat -c %u "/proc/$p" 2>/dev/null)" = "$uid" ] || return 1
		found=0
	done
	return "$found"
}

# http://localhost:8080 returns the content of /srv/webapp/index.html
serves_content() {
	local body
	body=$(curl -s -m 5 http://localhost:8080/ 2>/dev/null) || return 1
	[ "$body" = "$token" ]
}

# The directory and the index file have the type container_file_t
content_labeled() {
	local f
	for f in "$CONTENT" "$CONTENT/index.html"; do
		[ -e "$f" ] || return 1
		case "$(stat -c %C "$f" 2>/dev/null)" in
		*:container_file_t:*) ;;
		*) return 1 ;;
		esac
	done
}

# The user unit starts with the user manager: enabled (or generated by
# a quadlet file) and wanted by default.target
unit_enabled() {
	local wants
	case "$(as_user systemctl --user is-enabled "$UNIT")" in
	enabled | generated) ;;
	*) return 1 ;;
	esac
	wants=$(as_user systemctl --user show -p Wants --value default.target) || return 1
	case " $wants " in
	*" $UNIT "*) return 0 ;;
	esac
	return 1
}

unit_active() {
	as_user systemctl --user is-active --quiet "$UNIT"
}

# The container is the unit's main process (conmon), or its conmon runs
# in the unit's control group
container_in_unit() {
	local cpid mpid
	cpid=$(as_user podman inspect --type container --format '{{.State.ConmonPid}}' webapp) || return 1
	[ -n "$cpid" ] && [ "$cpid" != 0 ] || return 1
	mpid=$(as_user systemctl --user show -p MainPID --value "$UNIT") || return 1
	[ "$cpid" = "$mpid" ] && return 0
	grep -q "/$UNIT\(/\|$\)" "/proc/$cpid/cgroup" 2>/dev/null
}

criterion "Package podman is installed" rpm -q podman
criterion "Container webapp runs rootless as $user" container_running
criterion "TCP port 8080 is published by a process of $user" port_owned_by_user
criterion "http://localhost:8080 serves $CONTENT/index.html" serves_content
criterion "$CONTENT and its index.html have type container_file_t" content_labeled
criterion "User unit $UNIT is enabled" unit_enabled
criterion "User unit $UNIT is active" unit_active
criterion "Container webapp is run by $UNIT" container_in_unit
criterion "Linger is enabled for $user" test -e "/var/lib/systemd/linger/$user"
grade_end
