#!/bin/bash
# dns-05 grader
source /opt/linux-labs/lib/grading.sh

LAB="dns-05"
STATE=/opt/linux-labs/state/$LAB
ORIG=/opt/linux-labs/state/$LAB.orig
WWW=www.rockylinux.org
PUBLIC=rockylinux.org
FIELDS=connection.id,connection.uuid,connection.interface-name
FIELDS=$FIELDS,connection.autoconnect,ipv4.method,ipv4.addresses
FIELDS=$FIELDS,ipv4.gateway,ipv4.dns,ipv4.dns-search,ipv4.ignore-auto-dns
FIELDS=$FIELDS,ipv6.method,ipv6.dns,ipv6.dns-search,ipv6.ignore-auto-dns

grade_begin dns-05
grade_require_state dns-05 "$STATE/info"

info() {
	sed -n "s/^$1=//p" "$STATE/info" | head -n 1
}
uuid=$(info uuid)
con=$(info con)

# The same function as in setup.sh
profile_fields() {
	nmcli -g "$FIELDS" connection show uuid "$1" 2>/dev/null
}

public_resolves() {
	timeout 25 getent ahosts "$PUBLIC"
}

# At least one address, none in 192.0.2.0/24
www_real_address() {
	local addrs
	addrs=$(timeout 25 getent ahosts "$WWW" | awk '{ print $1 }' | sort -u)
	[ -n "$addrs" ] || return 1
	! printf '%s\n' "$addrs" | grep -q '^192\.0\.2\.'
}

# No active line of /etc/hosts names www.rockylinux.org
hosts_no_www() {
	awk -v n="$WWW" '
		{ sub(/#.*/, "") }
		NF >= 2 { for (i = 2; i <= NF; i++) if (tolower($i) == n) bad = 1 }
		END { exit bad }' /etc/hosts
}

# The active lines of a hosts file without www.rockylinux.org, fields
# separated by one space
hosts_lines() {
	awk -v n="$WWW" '
		{ sub(/#.*/, "") }
		NF == 0 { next }
		{ for (i = 2; i <= NF; i++) if (tolower($i) == n) next }
		{ $1 = $1; print }' "$1"
}

hosts_others_unchanged() {
	[ -r "$ORIG/hosts" ] || return 1
	[ "$(hosts_lines /etc/hosts)" = "$(hosts_lines "$ORIG/hosts")" ]
}

# Neither the immutable nor the append-only attribute on the file the
# path leads to. A file system without attributes (tmpfs, for a symlink
# to /run/NetworkManager/resolv.conf) cannot set them.
resolv_not_protected() {
	local f attrs
	f=$(readlink -f /etc/resolv.conf) || return 1
	[ -f "$f" ] || return 1
	attrs=$(lsattr -d "$f" 2>/dev/null | awk '{ print $1 }')
	case "$attrs" in
		*i* | *a*) return 1 ;;
	esac
}

resolv_by_nm() {
	[ "$(head -n 1 /etc/resolv.conf 2>/dev/null)" = "# Generated by NetworkManager" ]
}

resolv_nameservers() {
	local now
	now=$(awk '$1 == "nameserver" { print $2 }' /etc/resolv.conf 2>/dev/null | sort -u)
	[ -n "$now" ] && [ "$now" = "$(cat "$STATE/dns")" ]
}

# The [main] keys dns and rc-manager as NetworkManager reads them from
# its configuration files
nm_manages_dns() {
	local conf dns rc
	conf=$(NetworkManager --print-config 2>/dev/null) || return 1
	dns=$(printf '%s\n' "$conf" | awk -F= '
		/^\[/ { main = ($0 == "[main]") }
		main && $1 == "dns" { v = $2 }
		END { print v }')
	rc=$(printf '%s\n' "$conf" | awk -F= '
		/^\[/ { main = ($0 == "[main]") }
		main && $1 == "rc-manager" { v = $2 }
		END { print v }')
	[ "$dns" != none ] && [ "$rc" != unmanaged ]
}

profile_unchanged() {
	[ -n "$uuid" ] || return 1
	[ "$(profile_fields "$uuid")" = "$(cat "$STATE/profile")" ] || return 1
	if [ -s "$STATE/profile.sha256" ]; then
		sha256sum --quiet -c "$STATE/profile.sha256" || return 1
	fi
}

criterion "Public host names such as $PUBLIC resolve" public_resolves
criterion "$WWW resolves to its public address" www_real_address
criterion "/etc/hosts has no line for $WWW" hosts_no_www
criterion "The other lines of /etc/hosts are unchanged" hosts_others_unchanged
criterion "/etc/resolv.conf can be updated by NetworkManager" resolv_not_protected
criterion "/etc/resolv.conf is generated by NetworkManager" resolv_by_nm
criterion "/etc/resolv.conf lists the DNS servers of $con" resolv_nameservers
criterion "NetworkManager is configured to manage DNS" nm_manages_dns
criterion "The connection profile $con is unchanged" profile_unchanged
criterion "NetworkManager is active" systemctl is-active --quiet NetworkManager
grade_end
