#!/usr/bin/env bash
# Generate the lab catalog from labs/*/description.txt.
#
# Usage: scripts/gen-catalog.sh [--md <file> | --html <file>]
#
# Without arguments it writes docs/catalog.md. --md writes the same
# Markdown to another file (check-labs.sh uses this to compare). --html
# writes a small self-contained page for GitHub Pages (the release workflow
# publishes it as catalog.html; it is not committed).
#
# The output is deterministic: categories in alphabetical order, labs
# sorted by id, no timestamps. Runs on bash 3.2 (macOS) and later.

set -eu

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
MODE=md
OUT="$ROOT_DIR/docs/catalog.md"

usage() {
	echo "Usage: $0 [--md <file> | --html <file>]" >&2
}

case "${1:-}" in
	"") ;;
	--md|--html)
		if [ "$#" -ne 2 ] || [ -z "$2" ]; then
			usage
			exit 2
		fi
		MODE="${1#--}"
		OUT="$2"
		;;
	-h|--help) usage; exit 0 ;;
	*) echo "Error: unknown argument: $1" >&2; usage; exit 2 ;;
esac

# Value of one key in a lab's description.txt
field() {
	sed -n "s/^$2: //p" "$ROOT_DIR/labs/$1/description.txt" | head -n 1
}

# "internet, reboot, free-nic, nodes=3" -> "internet, reboot, free NIC, 3 nodes"
needs_text() {
	local v="$1" out="" item
	[ -n "$v" ] || { echo "-"; return; }
	for item in $(printf '%s\n' "$v" | tr -d ','); do
		case "$item" in
			free-nic) item="free NIC" ;;
			nodes=*) item="${item#nodes=} nodes" ;;
		esac
		out="${out:+$out, }$item"
	done
	echo "$out"
}

html_escape() {
	sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

TMP=$(mktemp "${TMPDIR:-/tmp}/gen-catalog.XXXXXX")
BODY=$(mktemp "${TMPDIR:-/tmp}/gen-catalog.XXXXXX")
trap 'rm -f "$TMP" "$BODY"' EXIT

# One record per lab: category|lab|title|level|course|needs
for d in "$ROOT_DIR"/labs/*/; do
	lab="${d%/}"
	lab="${lab##*/}"
	[ -f "$d/description.txt" ] || continue
	course=$(field "$lab" course)
	if [ -n "$course" ]; then
		course="$course $(field "$lab" course_lab)"
	else
		course="-"
	fi
	printf '%s|%s|%s|%s|%s|%s\n' "$(field "$lab" category)" "$lab" "$(field "$lab" title)" \
		"$(field "$lab" complexity)" "$course" "$(needs_text "$(field "$lab" needs)")"
done | LC_ALL=C sort -f -t'|' -k1,1 -k2,2 >"$TMP"

# Render the records. Arguments: heading-open, row format switch.
render() {
	local fmt="$1" prev="" cat lab title level course needs
	while IFS='|' read -r cat lab title level course needs; do
		if [ "$cat" != "$prev" ]; then
			if [ "$fmt" = html ]; then
				[ -z "$prev" ] || printf '</table>\n'
				printf '<h2>%s</h2>\n<table>\n<tr><th>Lab</th><th>Title</th><th>Level</th><th>Course</th><th>Needs</th></tr>\n' \
					"$(printf '%s' "$cat" | html_escape)"
			else
				[ -z "$prev" ] || printf '\n'
				printf '## %s\n\n| Lab | Title | Level | Course | Needs |\n|---|---|---|---|---|\n' "$cat"
			fi
			prev="$cat"
		fi
		if [ "$fmt" = html ]; then
			printf '<tr><td><code>%s</code></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n' \
				"$lab" "$(printf '%s' "$title" | html_escape)" "$level" "$course" "$needs"
		else
			printf '| %s | %s | %s | %s | %s |\n' "$lab" "$title" "$level" "$course" "$needs"
		fi
	done <"$TMP"
	[ "$fmt" != html ] || [ -z "$prev" ] || printf '</table>\n'
}

INTRO="Generated by scripts/gen-catalog.sh from labs/*/description.txt, do not edit by hand. Needs lists what the lab requires from the environment."

if [ "$MODE" = html ]; then
	render html >"$BODY"
	cat >"$TMP" <<HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>linux-labs catalog</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 60rem; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; color: #222; background: #fff; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.9rem; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 1rem; }
  th, td { text-align: left; padding: 0.25rem 0.5rem; border-bottom: 1px solid #ddd; vertical-align: top; }
  a { color: #0645ad; }
  @media (prefers-color-scheme: dark) {
    body { color: #ddd; background: #111; }
    th, td { border-bottom-color: #333; }
    a { color: #8ab4f8; }
  }
</style>
</head>
<body>
<h1>Lab catalog</h1>
<p><a href="./">Back to linux-labs</a>. Needs lists what the lab requires from the environment.</p>
HTML
	cat "$BODY" >>"$TMP"
	printf '</body>\n</html>\n' >>"$TMP"
else
	{
		printf '# Lab catalog\n\n%s\n\n' "$INTRO"
		render md
	} >"$BODY"
	cat "$BODY" >"$TMP"
fi

mkdir -p "$(dirname "$OUT")"
cat "$TMP" >"$OUT"
