#!/usr/bin/env bash
# Generate the lab catalog from labs/*/description.txt.
#
# Usage: scripts/gen-catalog.sh [--md <file> | --html <file>]
#
# Without arguments it writes docs/catalog.md. --md writes the same
# Markdown to another file (check-labs.sh uses this to compare). --html
# writes the catalog page for GitHub Pages with the site header and footer;
# it links site.css and keeps the @VERSION@ placeholder, which
# scripts/update-pages.sh fills in (the release workflow publishes it as
# catalog.html; it is not committed).
#
# The output is deterministic: categories in alphabetical order, labs
# sorted by id, no timestamps. Runs on bash 3.2 (macOS) and later.

set -eu

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
MODE=md
ISSUES_URL="https://github.com/matej-basic/linux-labs/blob/main/labs"
OUT="$ROOT_DIR/docs/catalog.md"

usage() {
	echo "Usage: $0 [--md <file> | --html <file>]" >&2
}

case "${1:-}" in
	"") ;;
	--md|--html)
		if [ "$#" -ne 2 ] || [ -z "$2" ]; then
			usage
			exit 2
		fi
		MODE="${1#--}"
		OUT="$2"
		;;
	-h|--help) usage; exit 0 ;;
	*) echo "Error: unknown argument: $1" >&2; usage; exit 2 ;;
esac

# Value of one key in a lab's description.txt
field() {
	sed -n "s/^$2: //p" "$ROOT_DIR/labs/$1/description.txt" | head -n 1
}

# "internet, reboot, free-nic, nodes=3" -> "internet, reboot, free NIC, 3 nodes"
needs_text() {
	local v="$1" out="" item
	[ -n "$v" ] || { echo "-"; return; }
	for item in $(printf '%s\n' "$v" | tr -d ','); do
		case "$item" in
			free-nic) item="free NIC" ;;
			nodes=*) item="${item#nodes=} nodes" ;;
		esac
		out="${out:+$out, }$item"
	done
	echo "$out"
}

# Known issues of a lab: counts the open and workaround entries of
# labs/<lab>/known-issues.md ("- DATE | RELEASES | STATUS | text"); fixed
# entries are history and not counted. Prints "-" for none, else for example
# "1 open, 1 workaround".
issues_text() {
	local f="$ROOT_DIR/labs/$1/known-issues.md" out
	[ -f "$f" ] || { echo "-"; return; }
	out=$(awk '
		/^- / { split(substr($0, 3), p, "[ ][|][ ]"); if (p[3] == "open") o++; else if (p[3] == "workaround") w++ }
		END {
			if (o) printf "%d open", o
			if (o && w) printf ", "
			if (w) printf "%d workaround", w
		}
	' "$f")
	echo "${out:--}"
}

html_escape() {
	sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

# "High Availability Clustering" -> "high-availability-clustering"
slug() {
	printf '%s' "$1" | LC_ALL=C tr '[:upper:]' '[:lower:]' | LC_ALL=C tr -c 'a-z0-9' '-'
}

TMP=$(mktemp "${TMPDIR:-/tmp}/gen-catalog.XXXXXX")
BODY=$(mktemp "${TMPDIR:-/tmp}/gen-catalog.XXXXXX")
trap 'rm -f "$TMP" "$BODY"' EXIT

# One record per lab: category|lab|title|level|target|course|needs|known issues
for d in "$ROOT_DIR"/labs/*/; do
	lab="${d%/}"
	lab="${lab##*/}"
	[ -f "$d/description.txt" ] || continue
	course=$(field "$lab" course)
	if [ -n "$course" ]; then
		course="$course $(field "$lab" course_lab)"
	else
		course="-"
	fi
	target=$(field "$lab" target)
	[ -n "$target" ] || target="nodes"
	printf '%s|%s|%s|%s|%s|%s|%s|%s\n' "$(field "$lab" category)" "$lab" "$(field "$lab" title)" \
		"$(field "$lab" complexity)" "$target" "$course" "$(needs_text "$(field "$lab" needs)")" "$(issues_text "$lab")"
done | LC_ALL=C sort -f -t'|' -k1,1 -k2,2 >"$TMP"

# Render the records. Arguments: heading-open, row format switch.
render() {
	local fmt="$1" prev="" cat lab title level target course needs issues url
	while IFS='|' read -r cat lab title level target course needs issues; do
		url="$ISSUES_URL/$lab/known-issues.md"
		if [ "$cat" != "$prev" ]; then
			if [ "$fmt" = html ]; then
				[ -z "$prev" ] || printf '</tbody>\n</table>\n</div>\n'
				printf '<h2 id="%s">%s</h2>\n<div class="table-wrap">\n<table class="labs">\n<thead><tr><th scope="col">Lab</th><th scope="col">Title</th><th scope="col">Level</th><th scope="col">Target</th><th scope="col">Course</th><th scope="col">Needs</th><th scope="col">Known issues</th></tr></thead>\n<tbody>\n' \
					"$(slug "$cat")" "$(printf '%s' "$cat" | html_escape)"
			else
				[ -z "$prev" ] || printf '\n'
				printf '## %s\n\n| Lab | Title | Level | Target | Course | Needs | Known issues |\n|---|---|---|---|---|---|---|\n' "$cat"
			fi
			prev="$cat"
		fi
		if [ "$issues" != "-" ]; then
			if [ "$fmt" = html ]; then
				issues="<a href=\"$url\">$issues</a>"
			else
				issues="[$issues]($url)"
			fi
		fi
		if [ "$fmt" = html ]; then
			printf '<tr><td><code>%s</code></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n' \
				"$lab" "$(printf '%s' "$title" | html_escape)" "$level" "$target" "$course" "$needs" "$issues"
		else
			printf '| %s | %s | %s | %s | %s | %s | %s |\n' "$lab" "$title" "$level" "$target" "$course" "$needs" "$issues"
		fi
	done <"$TMP"
	[ "$fmt" != html ] || [ -z "$prev" ] || printf '</tbody>\n</table>\n</div>\n'
}

INTRO="Generated by scripts/gen-catalog.sh from labs/*/description.txt, do not edit by hand. Target is the machine the lab runs on (servera), or nodes for multi-node labs, which run on the workstation and reach their nodes themselves. Needs lists what the lab requires from the environment. Known issues counts the open and workaround entries in the known-issues.md of each lab."

if [ "$MODE" = html ]; then
	render html >"$BODY"
	count=$(wc -l <"$TMP" | tr -d ' ')
	toc=$(cut -d'|' -f1 "$TMP" | uniq | while IFS= read -r cat; do
		printf '<li><a href="#%s">%s</a></li>' "$(slug "$cat")" "$(printf '%s' "$cat" | html_escape)"
	done)
	cat >"$TMP" <<HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lab catalog - linux-labs</title>
<meta name="description" content="All $count linux-labs labs by category, with level, target, course, what each lab needs and known issues.">
<meta name="color-scheme" content="light dark">
<link rel="stylesheet" href="site.css">
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<header class="top">
  <a class="brand" href="./">linux<span>-</span>labs</a>
  <nav aria-label="Main">
    <ul>
      <li><a href="./#install">Install</a></li>
      <li><a href="catalog.html" aria-current="page">Catalog</a></li>
      <li><a href="docs/getting-started.html">Docs</a></li>
      <li><a href="https://github.com/matej-basic/linux-labs">GitHub</a></li>
    </ul>
  </nav>
</header>

<main id="main" class="page">
<h1>Lab catalog</h1>
<p class="lead">All $count labs by category. Start one with <code>sudo labctl start &lt;lab&gt;</code>. Needs lists what a lab requires from your machine, for example internet access or extra nodes.</p>
<nav aria-label="Categories">
<ul class="subnav">$toc</ul>
</nav>
HTML
	cat "$BODY" >>"$TMP"
	cat >>"$TMP" <<'HTML'
</main>

<footer class="foot">
  <span>linux-labs @VERSION@ &middot; <a href="catalog.html">Catalog</a> &middot; <a href="docs/getting-started.html">Docs</a> &middot; Stuck? <code>labctl hint &lt;lab&gt;</code></span>
  <span><a href="https://github.com/matej-basic/linux-labs">GitHub</a></span>
</footer>
</body>
</html>
HTML
else
	{
		printf '# Lab catalog\n\n%s\n\n' "$INTRO"
		render md
	} >"$BODY"
	cat "$BODY" >"$TMP"
fi

mkdir -p "$(dirname "$OUT")"
cat "$TMP" >"$OUT"
