#!/usr/bin/env bash
set -euo pipefail

# Build the GitHub Pages site into a checkout of the gh-pages branch: add
# signed RPMs, refresh the dnf repo metadata and write the web pages. Used by
# .github/workflows/rpm.yml; git commit and push are left to the caller.
# scripts/preview-pages.sh runs it with --no-rpm for a local preview.
#
# Usage: update-pages.sh <gh-pages dir> <signed.rpm>...
#        update-pages.sh --no-rpm <dir>
#
# --no-rpm skips the dnf repository (no RPMs, no createrepo_c) and writes
# only the files below that are not under rpm/.
#
# Layout written into <gh-pages dir>:
#   rpm/*.rpm, rpm/repodata/   dnf repository (every released RPM is kept)
#   install                    copy of pages/install.sh
#   linux-labs.repo            .repo file for manual installs
#   RPM-GPG-KEY-linux-labs     public signing key (pages/RPM-GPG-KEY-linux-labs)
#   index.html, site.css       front page and shared styles, from pages/
#   catalog.html               lab catalog, generated by gen-catalog.sh --html
#   docs/<name>.html           docs/student/<name>.md rendered with pandoc
#   .nojekyll
#
# In every HTML page @VERSION@ becomes the Version: of rpm/linux-labs.spec
# and @LAB_COUNT@ the number of labs.
#
# pandoc: $PANDOC if set, else pandoc from PATH, else the pandoc/core
# docker image.

usage() {
        echo "Usage: $0 <gh-pages dir> <signed.rpm>..." >&2
        echo "       $0 --no-rpm <dir>" >&2
}

WITH_RPM=true
if [[ "${1:-}" == "--no-rpm" ]]; then
        WITH_RPM=false
        shift
        if [[ $# -ne 1 ]]; then
                usage
                exit 1
        fi
elif [[ $# -lt 2 ]]; then
        usage
        exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
SITE_DIR="$1"
shift

if [[ ! -d "$SITE_DIR" ]]; then
        echo "Error: gh-pages directory not found: $SITE_DIR" >&2
        exit 1
fi

VERSION="$(awk '/^Version:/ {print $2; exit}' "$ROOT_DIR/rpm/linux-labs.spec")"
if [[ -z "$VERSION" ]]; then
        echo "Error: no Version: line in rpm/linux-labs.spec" >&2
        exit 1
fi
LAB_COUNT="$(find "$ROOT_DIR/labs" -mindepth 2 -maxdepth 2 -name description.txt | wc -l | tr -d ' ')"

# Pick pandoc before changing anything in the site directory
if [[ -n "${PANDOC:-}" ]]; then
        read -r -a PANDOC_CMD <<<"$PANDOC"
elif command -v pandoc >/dev/null 2>&1; then
        PANDOC_CMD=(pandoc)
elif command -v docker >/dev/null 2>&1; then
        # Input files are read from the checkout, output goes to stdout
        PANDOC_CMD=(docker run --rm -v "$ROOT_DIR:$ROOT_DIR:ro" -w "$ROOT_DIR" pandoc/core)
else
        echo "Error: pandoc not found (install pandoc or docker)" >&2
        exit 1
fi

if $WITH_RPM; then
        if ! command -v createrepo_c >/dev/null 2>&1; then
                echo "Error: createrepo_c not found" >&2
                exit 1
        fi

        mkdir -p "$SITE_DIR/rpm"
        for rpm_file in "$@"; do
                echo "==> Adding $(basename "$rpm_file") to $SITE_DIR/rpm/"
                cp "$rpm_file" "$SITE_DIR/rpm/"
        done

        if [[ -d "$SITE_DIR/rpm/repodata" ]]; then
                echo "==> Updating repo metadata"
                createrepo_c --update "$SITE_DIR/rpm"
        else
                echo "==> Creating repo metadata"
                createrepo_c "$SITE_DIR/rpm"
        fi
fi

# Fill in the placeholders of one HTML page (stdin to stdout)
fill() {
        sed -e "s/@VERSION@/$VERSION/g" -e "s/@LAB_COUNT@/$LAB_COUNT/g"
}

echo "==> Writing site files (version $VERSION, $LAB_COUNT labs)"
cp "$ROOT_DIR/pages/install.sh" "$SITE_DIR/install"
cp "$ROOT_DIR/pages/RPM-GPG-KEY-linux-labs" "$SITE_DIR/RPM-GPG-KEY-linux-labs"
cp "$ROOT_DIR/pages/linux-labs.repo" "$SITE_DIR/linux-labs.repo"
cp "$ROOT_DIR/pages/site.css" "$SITE_DIR/site.css"
fill <"$ROOT_DIR/pages/index.html" >"$SITE_DIR/index.html"

catalog_tmp="$(mktemp "${TMPDIR:-/tmp}/catalog.XXXXXX")"
trap 'rm -f "$catalog_tmp"' EXIT
"$ROOT_DIR/scripts/gen-catalog.sh" --html "$catalog_tmp"
fill <"$catalog_tmp" >"$SITE_DIR/catalog.html"

# Student guides. docs/ on gh-pages is written only here, so a guide that
# was removed from docs/student/ also disappears from the site.
rm -rf "$SITE_DIR/docs"
mkdir -p "$SITE_DIR/docs"
for md in "$ROOT_DIR"/docs/student/*.md; do
        name="$(basename "$md" .md)"
        title="$(sed -n '1s/^# //p' "$md")"
        echo "==> Rendering docs/$name.html"
        "${PANDOC_CMD[@]}" --from gfm --to html5 --standalone \
                --template "$ROOT_DIR/pages/doc-template.html" \
                --lua-filter "$ROOT_DIR/pages/doc-links.lua" \
                --metadata pagetitle="${title:-$name}" \
                --metadata description="linux-labs student guide: ${title:-$name}" \
                --metadata "nav-$name=true" \
                "$md" | fill >"$SITE_DIR/docs/$name.html"
done

touch "$SITE_DIR/.nojekyll"

echo "==> gh-pages content ready in $SITE_DIR"
